name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ghcr.io/<{GITHUB_REPOSITORY}>:<{GITHUB_WORKFLOW_SHA}>, ghcr.io/<{GITHUB_REPOSITORY}>:latest
